---
- name: Install MariaDB packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - mariadb-server
  when: ansible_os_family == "RedHat"
  sudo: yes

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
  sudo: yes