---
##
# MariaDB database setup, this does the equivalent of mysql_secure_installation.
#
# Inspired by:
#  - https://github.com/ayn/ansible-playbooks/blob/master/common-tasks/mysql-secure.yml
#  - https://coderwall.com/p/yez9yw
##

- name: Install MySQL Python
  yum:
    name: MySQL-python
    state: present
  when: ansible_os_family == "RedHat"
  sudo: yes

- name: Start MariaDB
  service:
    name: mariadb
    state: started
  sudo: yes

- name: Set root password for all root accounts
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  sudo: yes

- name: Copy .my.cnf with root password credentials
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  sudo: yes
  notify: restart mariadb

- name: Delete anonymous users
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
  sudo: yes

- name: Remove test database
  mysql_db:
    db: test
    state: absent
  sudo: yes