---
- name: PHP-FPM Set option - listen
  ini_file:
    dest: /etc/php-fpm.d/www.conf
    section: www
    option: listen
    value: "127.0.0.1:9000"
    state: present
  when: php_enable_php_fpm
  sudo: yes