---
# Include OS-specific variables.
#- include_vars: "{{ ansible_os_family }}.yml"

#- name: Define php_packages
#  set_fact:
#    php_packages: "{{ php_packages | list }}"
#  when: php_packages is not defined

- name: Install PHP packages (RedHat)
  yum:
    name: "{{ item }}"
    state: present
  with_items: php_packages
  when: ansible_os_family == "RedHat"
  sudo: yes

- name: Install PHP packages (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items: php_packages
  when: ansible_os_family == 'Debian'
  sudo: yes

- include: ./configure-php.yml

- include: ./configure-php-fpm.yml
  when: php_enable_php_fpm

- name: Start PHP-FPM (if configured)
  service:
    name: php-fpm
    state: started
    enabled: yes
  when: php_enable_php_fpm
  sudo: yes