---
- name: start mariadb
  service:
    name: mariadb
    state: started
  sudo: yes

- name: stop mariadb
  service:
    name: mariadb
    state: stopped
  sudo: yes

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
  sudo: yes

- name: reload mariadb
  service:
    name: mariadb
    state: reloaded
  sudo: yes