---
- name: start php-fpm
  service:
    name: php-fpm
    state: started
  when: php_enable_php_fpm
  sudo: yes

- name: stop php-fpm
  service:
    name: php-fpm
    state: stopped
  when: php_enable_php_fpm
  sudo: yes

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
  when: php_enable_php_fpm
  sudo: yes

- name: reload php-fpm
  service:
    name: php-fpm
    state: reloaded
  when: php_enable_php_fpm
  sudo: yes