---
# http://wiki.nginx.org/Install
- name: Add Nginx Repository
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
  when: ansible_os_family == "RedHat"
  sudo: yes

- name: Install Nginx
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"
  sudo: yes

- name: Set Nginx Default Server Block
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 644
  sudo: yes

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  sudo: yes